name: SonarCloud

on:
  push:
    branches: [ 'main' ]
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened' ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPUnit with coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=test.xml

      - name: Fix paths in coverage reports for Sonar
        run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' test.xml

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}